# Basic service configuration
name: Centurion
type: homebrew

build:
  language: go
  version: "1.23"     # Go version to use (useful if you need different versions)
  cmd: "go build -o ./dist"
  env_vars:
    CGO_ENABLED: '0'
    GOOS: linux
    GOARCH: amd64
  flags:
    ldflags:
      - "-s"
      - "-w"
      - "-extldflags '-static'"
