# Pilum deploys itself
name: pilum
type: homebrew
description: Multi-cloud deployment CLI - define once, deploy anywhere
license: BSL-1.1

homebrew:
  project_url: https://github.com/SID-Technologies/pilum
  tap_url: https://github.com/SID-Technologies/Homebrew-Pilum
  token_env: GH_TOKEN

build:
  language: go
  version: "1.23"
  version_var: github.com/sid-technologies/pilum/cmd.version
  output: dist/pilum
  env_vars:
    CGO_ENABLED: "0"
  platforms:
    - os: darwin
      arch: amd64
    - os: darwin
      arch: arm64
    - os: linux
      arch: amd64
    - os: linux
      arch: arm64
